version: 0.0
os: linux
files:
  - source: /magento
    destination: /var/www/html/ 
  - source: script/install_dependencies
    destination: /var/www/html/
permissions:
  - object: /var/www/html/magento/
    mode: 777
hooks:
    BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
